# Generated by Django 5.0.1 on 2024-01-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
